[package]
name = "Srp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hacspec-lib = { path = "../../Hacspec/lib" }
hacspec-sha256 = { path = "../../Hacspec/examples/sha256" }