[package]
name = "Diffiehellman"
version = "0.1.0"
edition = "2021"

[lib]
path = "rs_src/diffiehellman.rs"

[dependencies]
rand = "0.8"
num-bigint = { version = "0.4", features = ["rand"] }
hacspec-lib = { path = "../../hacspec/lib" }
